class TransactionPool:
    def __init__(self):
        self.transaction_map = {}
    
    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool.
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a tranaction generated by the address in the transaction pool.
        """
        # if there is no matching value, will return "None"
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction